[colors.primary]
background = '#141218'
foreground = '#e6e0e9'

[colors.selection]
text = '#e6e0e9'
background = '#4f378b'

[colors.cursor]
text = '#141218'
cursor = '#d0bcff'

[colors.normal]
black   = '#141218'
red     = '#8c150b'
green   = '#09720f'
yellow  = '#7f7d11'
blue    = '#8754ff'
magenta = '#44298b'
cyan    = '#6750A4'
white   = '#1a1a1a'

[colors.bright]
black   = '#2e2e2e'
red     = '#a52a20'
green   = '#138c1a'
yellow  = '#999621'
blue    = '#7455c4'
magenta = '#4f3fff'
cyan    = '#d459ff'
white   = '#1a1a1a'
